### ISSUE TITLE
Inaccurate license information

### ISSUE THREAD

**Issue by JakubVanek** [CreativeInquiry/PEmbroider#94]
Hi all,

the README reads that 

> PEmbroider is free, open-source software released under the Anti-Capitalist Software License.

However, the ACSL website claims otherwise:

> The Anti-Capitalist Software License is not an open source software license. It does not allow unrestricted use by any group in any field of endeavor, an allowance that further entrenches established powers.

This was discovered in the discussion under https://www.abclinuxu.cz/zpravicky/pembroider-nova-knihovna-pro-processing-urcena-pro-navrh-vysivek-pro-vysivaci-stroje.

Best regards,

Jakub

**Comment by JakubVanek** [comment]
This also breaks https://github.com/CreativeInquiry/PEmbroider#motivation, as this library is not OSS either.

**Comment by LingDong-** [comment]
@golanlevin 


----

How about GPL or LGPL? I think the requirement that derivative work must also be open source is inherently anti-capitalist. Processing is GPL.

🤷‍♂️

**Comment by JakubVanek** [comment]
> How about GPL or LGPL? I think the requirement that derivative work must also be open source is inherently anti-capitalist. Processing is GPL.

IANAL, but I think that the derived work condition applies only to the program itself and not to the works generated by the program's operation (https://softwareengineering.stackexchange.com/a/311087 seems to agree).

**Comment by golanlevin** [comment]
OK. I have changed the license to a Frankenstein that combines GPLv3 with Anti-Capitalist Software License v.1.4; this has been updated [here](https://github.com/CreativeInquiry/PEmbroider#license) and [here](https://github.com/CreativeInquiry/PEmbroider/blob/master/license.txt). I do not believe they are in conflict, since the ACSL is concerned with different things than the GPL. 

@JakubVanek, I appreciate you flagging this issue. It is important to understand the reason we made PEmbroidery, which is that commercial embroidery software costs THOUSANDS of dollars, and has profiteering schemes like, it's an extra $100 to be able to add *lettering*, an extra $350 to edit shapes, and an extra $950 to add *outlines*. We believe that creating your own designs for your embroidery machine shouldn't require monthly financing. Thus, a quick summary of the kind of uses we are trying to encourage, prevent, and enforce would be as follows: 

* users/developers are _encouraged_ to use PEmbroider to make art;
* users/developers are _required_ to share your improvements to PEmbroider;
* users/developers are expressly _forbidden_ from using PEmbroider to profiteer on the backs of artists, craftspersons, educators, makers, and schools. An example of this would be using PEmbroider to make commercial software such as (e.g.) Floriani Total Control Embroidery Software ($3499), DIME Designs in Machine Embroidery ($2999), Viking Premier Plus 2 Ultra ($2979), Hatch Embroidery Digitizer ($1099), Janome Artistic Digitizer Software ($1199), DesignerPlus Full Version ($1874), DRAWings PRO XI ($1299), _etcetera_.
